service: forex

frameworkVersion: "<=1.6.1"

custom:
  namespace: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  environment:
    CLIENT_ID: "165858646675.192416803751"
    CLIENT_SECRET: 4409f241333e4140411eae196bfc39f6
    VERIFICATION_TOKEN: qOP3Iz1Iob1t5nisZHk40zTC
    SUCCESS_URL: https://s3.amazonaws.com/mypoeticbucket/success.html
    ERROR_URL: https://s3.amazonaws.com/mypoeticbucket/error.html
    NAMESPACE: ${self:custom.namespace}
    TEAMS_TABLE: ${self:custom.namespace}-teams
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.TEAMS_TABLE}
    - Effect: Allow
      Action:
        - lambda:invokeFunction
      Resource:
        - arn:aws:lambda:*:*:function:${self:custom.namespace}-actions

functions:
  actions:
    handler: actions.handler
  events:
    handler: events.handler
    events:
      - http:
          path: events
          method: post
  install:
    handler: install.handler
    events:
      - http:
          path: install
          method: get

resources:
  Resources:
    TeamsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEAMS_TABLE}
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
